using System;
using System.Collections.Generic;
using SynapticSea.Core.Variant;
using UnityEngine;

namespace SynapticSea.Runtime
{
    /// <summary>
    /// id → VFX prefab lookup (<c>Resources/Catalogs/VfxCatalog</c>), regenerated by the editor VfxPrefabBuilder from
    /// the Godot <c>scenes/vfx/*.tscn</c>. The ids are the scene file names. At 96ecb2b0 no Godot script instanced
    /// these scenes; each entry's <c>usage</c> records the gameplay element it was authored for, so the gameplay port
    /// can wire it through <see cref="Spawn"/>.
    /// </summary>
    [CreateAssetMenu(menuName = "Synaptic Sea/VFX Catalog", fileName = "VfxCatalog")]
    public sealed class VfxCatalog : ScriptableObject
    {
        public const string ResourcePath = "Catalogs/VfxCatalog";

        public const string TimedFire = "timed_fire";
        public const string BeaconBlue = "beacon_blue";
        public const string ReactorGreen = "reactor_green";
        public const string BiomatterBlockage = "biomatter_blockage";

        [Serializable]
        public sealed class Entry
        {
            public string id;
            public GameObject prefab;
            public string godotScene;
            public string usage;
        }

        public List<Entry> entries = new List<Entry>();

        Dictionary<string, Entry> _lookup;
        static VfxCatalog _loaded;

        public IEnumerable<string> Ids
        {
            get { foreach (var e in entries) if (e != null) yield return e.id; }
        }

        public bool TryGet(string id, out Entry entry)
        {
            if (_lookup == null)
            {
                _lookup = new Dictionary<string, Entry>(StringComparer.Ordinal);
                foreach (var e in entries)
                    if (e != null && !string.IsNullOrEmpty(e.id) && e.prefab != null) _lookup[e.id] = e;
            }
            return _lookup.TryGetValue(id ?? string.Empty, out entry);
        }

        void OnValidate() => _lookup = null;

        /// <summary>The catalog asset under Resources (cached).</summary>
        public static VfxCatalog Load() => _loaded != null ? _loaded : _loaded = Resources.Load<VfxCatalog>(ResourcePath);

        /// <summary>
        /// Instantiates VFX <paramref name="id"/> under <paramref name="parent"/> at a Godot-frame position local to the
        /// parent (e.g. a <see cref="ShipView"/> spec position). Returns null for an unknown id.
        /// </summary>
        public static GameObject Spawn(string id, Transform parent, Vec3 godotPosition)
        {
            var catalog = Load();
            if (catalog == null || !catalog.TryGet(id, out Entry entry)) return null;
            var instance = Instantiate(entry.prefab, parent, false);
            instance.name = entry.prefab.name;
            instance.transform.localPosition = Frame.ToUnity(godotPosition);
            var effect = instance.GetComponent<VfxEffect>();
            if (effect != null) effect.ApplyLightEnergies(); // also correct in edit mode, where OnEnable does not run
            return instance;
        }
    }
}
