using System;
using System.Collections.Generic;
using UnityEngine;

namespace SynapticSea.Runtime
{
    /// <summary>
    /// Maps the Godot icon resource paths data references (<c>res://assets/ui/status/*.png</c>,
    /// <c>res://assets/ui/achievements/*.png</c>) onto imported textures. Item icons
    /// (<c>res://assets/icons/**</c>, <c>res://assets/placeholder/&lt;item&gt;.png</c>) exist in neither engine, so they
    /// resolve to a per-category placeholder; each unresolved path is logged once. Regenerated by the Editor
    /// IconCatalogBuilder into <c>Resources/Catalogs/IconCatalog.asset</c>.
    /// </summary>
    [CreateAssetMenu(menuName = "Synaptic Sea/Icon Catalog", fileName = "IconCatalog")]
    public sealed class IconCatalog : ScriptableObject
    {
        public const string ResourcePath = "Catalogs/IconCatalog";

        /// <summary>Category used when neither the hint nor the path names a known category.</summary>
        public const string GenericCategory = "item";

        [Serializable]
        public sealed class Entry
        {
            public string resPath;
            public Texture2D texture;
        }

        [Serializable]
        public sealed class CategoryEntry
        {
            public string category;
            public Texture2D texture;
        }

        public List<Entry> entries = new List<Entry>();
        public List<CategoryEntry> categories = new List<CategoryEntry>();

        /// <summary>Godot icon folder (the path segment before the file) → placeholder category, for calls without a hint.</summary>
        public static readonly IReadOnlyDictionary<string, string> FolderCategories = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "materials", "raw" },
            { "loot", "unique" },
            { "placeholder", GenericCategory },
        };

        Dictionary<string, Texture2D> _byPath;
        Dictionary<string, Texture2D> _byCategory;
        readonly HashSet<string> _loggedUnresolved = new HashSet<string>(StringComparer.Ordinal);

        static IconCatalog _default;

        /// <summary>The <c>Resources/Catalogs/IconCatalog</c> asset (cached); tests may replace it.</summary>
        public static IconCatalog Default
        {
            get
            {
                if (_default == null) _default = Resources.Load<IconCatalog>(ResourcePath);
                return _default;
            }
            set => _default = value;
        }

        /// <summary>
        /// Texture for a Godot icon path through <see cref="Default"/>. Exact textures win; otherwise the placeholder for
        /// <paramref name="categoryHint"/> (item category), then for the path's folder, then the generic item
        /// placeholder. Null only for an empty path or a missing catalog.
        /// </summary>
        public static Texture2D Resolve(string resPath, string categoryHint = null)
        {
            IconCatalog catalog = Default;
            return catalog != null ? catalog.Lookup(resPath, categoryHint) : null;
        }

        /// <summary>Instance form of <see cref="Resolve"/>.</summary>
        public Texture2D Lookup(string resPath, string categoryHint = null)
        {
            BuildLookups();
            if (!string.IsNullOrEmpty(resPath) && _byPath.TryGetValue(resPath, out Texture2D exact)) return exact;
            if (string.IsNullOrEmpty(resPath) && string.IsNullOrEmpty(categoryHint)) return null;

            if (!string.IsNullOrEmpty(resPath) && _loggedUnresolved.Add(resPath))
                Debug.Log($"[IconCatalog] no texture for '{resPath}'; using the '{PlaceholderCategoryFor(resPath, categoryHint)}' placeholder");
            return GetCategoryPlaceholder(PlaceholderCategoryFor(resPath, categoryHint));
        }

        /// <summary>True when the path maps to an imported texture (not a placeholder).</summary>
        public bool HasExact(string resPath)
        {
            BuildLookups();
            return !string.IsNullOrEmpty(resPath) && _byPath.ContainsKey(resPath);
        }

        public bool HasCategory(string category)
        {
            BuildLookups();
            return !string.IsNullOrEmpty(category) && _byCategory.ContainsKey(category);
        }

        /// <summary>The placeholder for a category, or the generic item placeholder.</summary>
        public Texture2D GetCategoryPlaceholder(string category)
        {
            BuildLookups();
            if (!string.IsNullOrEmpty(category) && _byCategory.TryGetValue(category, out Texture2D tex)) return tex;
            return _byCategory.TryGetValue(GenericCategory, out Texture2D generic) ? generic : null;
        }

        /// <summary>Paths that fell back to a placeholder since load (diagnostics).</summary>
        public IReadOnlyCollection<string> UnresolvedPaths => _loggedUnresolved;

        string PlaceholderCategoryFor(string resPath, string categoryHint)
        {
            if (HasCategory(categoryHint)) return categoryHint;
            string folder = FolderOf(resPath);
            return FolderCategories.TryGetValue(folder, out string category) ? category : GenericCategory;
        }

        static string FolderOf(string resPath)
        {
            if (string.IsNullOrEmpty(resPath)) return "";
            int slash = resPath.LastIndexOf('/');
            if (slash <= 0) return "";
            int prev = resPath.LastIndexOf('/', slash - 1);
            return resPath.Substring(prev + 1, slash - prev - 1);
        }

        void BuildLookups()
        {
            if (_byPath != null) return;
            _byPath = new Dictionary<string, Texture2D>(StringComparer.Ordinal);
            _byCategory = new Dictionary<string, Texture2D>(StringComparer.Ordinal);
            foreach (Entry e in entries)
                if (e != null && !string.IsNullOrEmpty(e.resPath) && e.texture != null) _byPath[e.resPath] = e.texture;
            foreach (CategoryEntry c in categories)
                if (c != null && !string.IsNullOrEmpty(c.category) && c.texture != null) _byCategory[c.category] = c.texture;
        }

        void OnValidate()
        {
            _byPath = null;
            _byCategory = null;
        }
    }
}
