using System;
using System.Collections.Generic;
using UnityEngine;

namespace SynapticSea.Runtime
{
    /// <summary>
    /// module_id → prefab lookup for one structural kit. Regenerated by the Editor StructuralPrefabBuilder;
    /// the runtime ship builder never touches file paths.
    /// </summary>
    [CreateAssetMenu(menuName = "Synaptic Sea/Kit Catalog", fileName = "KitCatalog")]
    public sealed class KitCatalog : ScriptableObject
    {
        [Serializable]
        public sealed class Entry
        {
            public string moduleId;
            public StructuralModule prefab;
        }

        public string kitId;
        public float gridStepMetres = 4f;
        public List<Entry> modules = new List<Entry>();

        Dictionary<string, StructuralModule> _lookup;

        public bool TryGetPrefab(string moduleId, out StructuralModule prefab)
        {
            if (_lookup == null)
            {
                _lookup = new Dictionary<string, StructuralModule>(StringComparer.Ordinal);
                foreach (var e in modules)
                    if (e != null && !string.IsNullOrEmpty(e.moduleId) && e.prefab != null) _lookup[e.moduleId] = e.prefab;
            }
            return _lookup.TryGetValue(moduleId ?? string.Empty, out prefab);
        }

        void OnValidate() => _lookup = null;
    }
}
