using System;
using System.Collections.Generic;
using UnityEngine;

namespace SynapticSea.Runtime
{
    /// <summary>
    /// module_id → prefab lookup for one structural kit. Regenerated by the Editor StructuralPrefabBuilder;
    /// the runtime ship builder never touches file paths.
    /// Additive kits (ithappy_scifi_v0) live beside ship_structural_v0 as Resources/Catalogs/KitCatalog_{kit_id}.
    /// </summary>
    [CreateAssetMenu(menuName = "Synaptic Sea/Kit Prefab Catalog", fileName = "KitPrefabCatalog")]
    public sealed class KitPrefabCatalog : ScriptableObject
    {
        [Serializable]
        public sealed class Entry
        {
            public string moduleId;
            public StructuralModule prefab;
        }

        public string kitId;
        public float gridStepMetres = 4f;
        public List<Entry> modules = new List<Entry>();

        Dictionary<string, StructuralModule> _lookup;

        public bool TryGetPrefab(string moduleId, out StructuralModule prefab)
        {
            if (_lookup == null)
            {
                _lookup = new Dictionary<string, StructuralModule>(StringComparer.Ordinal);
                foreach (var e in modules)
                    if (e != null && !string.IsNullOrEmpty(e.moduleId) && e.prefab != null) _lookup[e.moduleId] = e.prefab;
            }
            if (_lookup.TryGetValue(moduleId ?? string.Empty, out prefab)) return true;
            // Additive kits (ithappy) are selectable before StructuralPrefabBuilder fills this
            // catalog: shared module_ids fall back to ship_structural_v0. Unique modules
            // (wall_x_junction) stay unresolved until the ithappy prefab exists.
            if (!string.IsNullOrEmpty(kitId) &&
                !string.Equals(kitId, "ship_structural_v0", StringComparison.Ordinal) &&
                !string.Equals(moduleId, "wall_x_junction", StringComparison.Ordinal))
            {
                var fallback = Resources.Load<KitPrefabCatalog>("Catalogs/KitCatalog_ship_structural_v0");
                if (fallback != null && fallback != this) return fallback.TryGetPrefab(moduleId, out prefab);
            }
            prefab = null;
            return false;
        }

        void OnValidate() => _lookup = null;
    }
}
