using System;
using System.Collections.Generic;
using UnityEngine;

namespace SynapticSea.Runtime
{
    /// <summary>
    /// (binding namespace, id) → prop prefab lookup, the replacement for Godot's PropVisualBindingCatalog +
    /// GLB PackedScene loads. Regenerated by the Editor PropPrefabBuilder.
    /// </summary>
    [CreateAssetMenu(menuName = "Synaptic Sea/Prop Catalog", fileName = "PropCatalog")]
    public sealed class PropCatalog : ScriptableObject
    {
        public List<PropVisual> props = new List<PropVisual>();

        Dictionary<string, PropVisual> _byBinding;
        Dictionary<string, PropVisual> _byAsset;

        static string Key(string ns, string id) => ns + "" + id;

        void Build()
        {
            _byBinding = new Dictionary<string, PropVisual>(StringComparer.Ordinal);
            _byAsset = new Dictionary<string, PropVisual>(StringComparer.Ordinal);
            foreach (var p in props)
            {
                if (p == null) continue;
                _byAsset[p.assetId] = p;
                if (p.bindingIds == null) continue;
                foreach (var id in p.bindingIds) _byBinding[Key(p.bindingNamespace, id)] = p;
            }
        }

        public bool TryGetByBinding(string bindingNamespace, string id, out PropVisual prefab)
        {
            if (_byBinding == null) Build();
            return _byBinding.TryGetValue(Key(bindingNamespace, id), out prefab);
        }

        public bool TryGetByAssetId(string assetId, out PropVisual prefab)
        {
            if (_byAsset == null) Build();
            return _byAsset.TryGetValue(assetId ?? string.Empty, out prefab);
        }

        void OnValidate()
        {
            _byBinding = null;
            _byAsset = null;
        }
    }
}
