import json,pathlib,hashlib,subprocess,collections
R=pathlib.Path(r'F:\tmp\synaptic-sea-playable');O=R/'docs/audit-deep/content';L=json.loads((O/'dependency-ledger.json').read_text());M=json.loads((O/'fresh-model-results.json').read_text());REV=L['summary']['revision'];BASE='8dcc95c10ab5e08658546319f51f49b4abd256fc'
def git(*a):return subprocess.check_output(['git','-c','safe.directory=F:/tmp/synaptic-sea-playable',*a],cwd=R,text=True).strip()
def evidence(p,sym):
 txt=(R/p).read_text(encoding='utf-8-sig');i=txt.find(sym);return {'file':p,'line':txt[:i].count('\n')+1,'symbol':sym,'revision':REV}
E=[evidence('SynapticSea/Assets/_Project/Core/Session/RunSession.Objectives.cs','TrainingEventBus?.Emit("repair_full_system"'),evidence('SynapticSea/Assets/_Project/Core/Session/RunSession.cs','OBJECTIVE_REPAIR_MAP'),evidence('SynapticSea/Assets/_Project/Core/Session/Interactables/RepairPoint.cs','PlayerProgression.GrantXp("repair", 25)'),evidence('SynapticSea/Assets/_Project/Core/Systems/Progression/PlayerProgressionState.cs','XpForNextLevel'),evidence('SynapticSea/Assets/_Project/Core/Systems/Progression/TrainingEventBus.cs','bool IsCrossTraining'),evidence('SynapticSea/Assets/_Project/UI/Menus/ClassPanel.cs','IsAvailable'),evidence('SynapticSea/Assets/_Project/Core/Session/RunSession.Save.cs','ClassIdsForTrigger')]
unlock={u.get('class_id'):u for u in json.loads((R/'SynapticSea/Assets/StreamingAssets/data/player/unlock_tables.json').read_text())['unlocks'] if u.get('category')=='class'}
classrows=[]
for r in M['class_rows']:
 c=next(c for c in L['classes'] if c['class_id']==r['class_id']);xpneed=max(0,sum((lev+1)*100 for lev in range(r['after_exact_two_onboarding_xp_events']['repair_level'],2))-r['after_exact_two_onboarding_xp_events']['repair_xp'])
 classrows.append({**r,'repair2_additional_effective_xp_after_objectives':xpneed,'starting_cooking':c['starting_skills'].get('cooking',0),'starting_first_aid':c['starting_skills'].get('first_aid',0),'title_initially_available':not c.get('unlockable',False),'title_unlock':unlock.get(c['class_id']),'unlock_applies':'EndRun folds logged trigger into MetaProgressionState; class catalog presence is not unlock','normal_source_notes':'Empty starting bag. Cache quantities are current LOCAL authored assets, physically acquired by searching maintenance cache; model directly provisions same contents as a diagnostic, not traversal. Before objectives only battery_cells and star_charts are repair1 source-feasible for low classes. Completing restore_systems force-repairs battery_cells, eliminating that training target. Later hazard-induced damage/random loot/hub bonus can change opportunities but are not assumed.','evidence':E})
# Exact all7 exchanges and paired craft/deconstruct net vectors. Single chosen output; batch size is NOT input multiplier.
pairs=[];non=[r for r in L['recipes'] if r['category']!='deconstruction'];decons=[r for r in L['recipes'] if r['category']=='deconstruction']
for r in decons:
 src=next(iter(r['ingredients']));makes=[c for c in non if c['produces']['item_id']==src];x={'deconstruct':r['recipe_id'],'inputs':r['ingredients'],'chosen_output':r['produces'],'authored_batch_size':r.get('batch_size',1),'live_station_duration_seconds':0,'live_skill_gate':False,'live_power_gate':False,'recipe_evidence':r['evidence'],'fresh_transaction':next(t for t in M['all7_deconstruction_station_transactions'] if t['recipe_id']==r['recipe_id']),'craft_roundtrips':[]}
 for c in makes:
  net=collections.Counter();net.update({k:-v for k,v in c['ingredients'].items()});net[c['produces']['item_id']]+=c['produces']['quantity'];net.update({k:-v for k,v in r['ingredients'].items()});net[r['produces']['item_id']]+=r['produces']['quantity'];net={k:v for k,v in net.items() if v};x['craft_roundtrips'].append({'craft_recipe':c['recipe_id'],'net_items':net,'self_sustaining_duplication':all(v>=0 for v in net.values()),'missing_normal_inputs':[k for k in c['ingredients'] if k in L['summary']['recipe_ingredients_outside_upper_bound_closure']],'evidence':c['evidence']})
 pairs.append(x)
files={e['file'] for group in ['findings','negative_findings'] for x in json.loads((O/'findings-and-traces.json').read_text())[group] for e in x['evidence']}|{e['file'] for e in E}|{'SynapticSea/Assets/StreamingAssets/data/player/classes.json','SynapticSea/Assets/StreamingAssets/data/items/loot_tables.json','SynapticSea/Assets/StreamingAssets/data/components/component_catalog.json','SynapticSea/Assets/StreamingAssets/data/procgen/golden/coherent_ship_001/gameplay_slice.json'}
comparison=[]
for file in sorted(files):
 try:old=git('rev-parse',BASE+':'+file)
 except subprocess.CalledProcessError:old=None
 try:new=git('rev-parse',REV+':'+file)
 except subprocess.CalledProcessError:new=None
 comparison.append({'file':file,'baseline_revision':BASE,'baseline_blob':old,'current_blob':new,'status':'identical_Git_blob' if old==new and old else 'added_local' if old is None else 'changed_local','note':'Changed file is not proof every cited method changed; consult exact diff. No local behavior is claimed published.'})
(O/'followup-class-deconstruction-baseline.json').write_text(json.dumps({'revision':REV,'published_baseline_revision':BASE,'all11_class_model_and_access_table':classrows,'all7_deconstruction_exchanges':pairs,'ingredient_schema':'All62 dicts: AND of every positive integer quantity.0 OR/alternative ingredient arrays. All62 provisioned exact-input CanCraft true at authored tier; every individual input reduced by1 rejects. Quantities are per transaction, batch_size metadata does not multiply live salvage inputs.','recipe_cycles':'SCCs are topology only. Direct seed membership does not bootstrap an AND recipe. Plating roundtrip gains scrap1 while consuming adhesive1; source of adhesive requires polymer3+reactivegel1, so this is resource conversion, not free duplication. Coolant synthesis needs coolant seed1 AND purifiedwater2 AND reactivegel1 to output2; no coolant seed source, so unavailable rather than free bootstrap.','cancel_save_laundering':'Fresh model begin cook_basic_meal consumes ration1+water1. Cancel leaves consumed bag empty, no output/refund; CancelCraft has no live Session/UI caller. Truthful craft+inventory JSON roundtrip at5/10seconds, then tick5, yields cooked_meal1, second FinishCraft empty. Reapplying an old whole snapshot is rollback, not additive duplication. Queue skip-consumption route has no live caller. Component provenance loss belongs to parent provisioned diagnostic; unavailable wrench limits normal access.','baseline_comparison':comparison,'baseline_recipe_count':60,'current_recipe_count':62,'local_recipe_additions':['craft_lockpick_set','craft_hack_chip'],'baseline_note':'Core progression/CraftingState/FieldCraftingState/DeconstructionResolver identical Git blobs. Current home explicit10stacks20units added locally; baseline home rolled repair_parts_starter. Never transfer guaranteed-local-cache access results to published baseline.'},indent=2)+'\n')
# Experiment manifest binds the actual fresh output and compiled binary, not an older build.
sourceManifest={str(p.relative_to(R)).replace('\\','/'):hashlib.sha256(p.read_bytes()).hexdigest() for p in (R/'SynapticSea/Assets/_Project/Core').rglob('*.cs')};dataManifest=json.loads((O/'data-file-hashes.json').read_text());canonical='\n'.join(k+' '+v for k,v in sorted({**sourceManifest,**dataManifest}.items()))
compiled=O/'bin/Debug/net8.0/ContentModels.dll'
manifest={'revision':REV,'tracked_dirty_files':git('diff','--name-only').splitlines(),'source_data_fingerprint_sha256':hashlib.sha256(canonical.encode()).hexdigest(),'source_sha256':sourceManifest,'compiled_artifact':str(compiled),'compiled_artifact_sha256':hashlib.sha256(compiled.read_bytes()).hexdigest(),'harness_sha256':hashlib.sha256((O/'Program.cs').read_bytes()).hexdigest(),'result_sha256':hashlib.sha256((O/'fresh-model-results.json').read_bytes()).hexdigest(),'SDK':'F:/Tools/dotnet/dotnet.exe8.0.425','command':'F:/Tools/dotnet/dotnet.exe run --project docs/audit-deep/content/ContentModels.csproj -- F:/tmp/synaptic-sea-playable F:/tmp/synaptic-sea-playable/docs/audit-deep/content','disposable_profile':'No storage/profile; isolated in-memory model objects only','seed':17,'classes':'all11 actual catalog classes, unlockable objects provisioned for diagnostic only','settings':'No Unity/player settings; base models; optional knowledge and tier explicitly set in tests; no hub bonuses','sequence':'Freshly compile current Core; load actual catalogs;11 Configure/Emit two onboarding events and alternate authored-cache repair order;62 exact ingredients and every missing-one test;7 immediate salvage transactions; unknown knowledge with/without gate; cancel consumption;5/10second JSONcraft restore then finish twice; installed tier2 direct vs spatial check.','expected':'AND missing-one rejection; salvage exact chosen outputs; no cancel refund; one output after truthful save restore; knowledge rejects when explicitly passed; spatial should respect effective tier2 if gate wiring correct','actual':'AND all passed62; salvage all7 succeeded exact outputs; cancel inputs stayed consumed; restore output1 then empty; explicit knowledge rejects/null ignores; effectiveTier2 directtrue spatialfalse; class exact outputs in fresh-model-results.json','evidence_scope':'Provisioned engine-free model transaction diagnostics, not normal play/traversal/frame/UI/store/published-build proof','Unity_executed':False,'user_save_writes':False}
(O/'fresh-model-experiment-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
lines=['# Class, exchange and baseline followup','',f'Current `{REV}`; published baseline `{BASE}`. Fresh engine-free diagnostics use current Core and actual catalogs. These are model diagnostics, not a natural onboarding walk.','', '| Class | Title fresh | Initial repair | After 2 onboarding events level / XP | Extra effective XP for repair2 | Cache repairs before objectives -> final level / XP |','|---|---|---:|---|---:|---|']
for r in classrows:
 st=r['initial'];on=r['after_exact_two_onboarding_xp_events'];alt=r['alternative_progression'];lines.append(f"| {r['class_id']} | {'locked' if r['unlockable'] else 'available'} | {st['repair_level']} | {on['repair_level']} / {on['repair_xp']} | {r['repair2_additional_effective_xp_after_objectives']} | {alt['repair_level']} / {alt['repair_xp']} |")
lines+=['','These two objective events correspond to restore_systems and stabilize_reactor. They each grant base repairXP120. Cross-category training halves that amount before the class technical multiplier. Level0->1 costs100 and1->2 costs200. RepairPoint completion additionally grants repairXP25 directly plus repair_subcomponent base50 through the bus.','', 'Current local cache provisions exactly20 units in10 stacks, after physical acquisition. With the condition1/seed17 manager and opening propulsion override, battery_cells and star_charts are the only repair1 targets compatible with these cache parts. Repairing both BEFORE onboarding enables pilot and salvage_captain to reach repair2; security ends2XP short and medic46XP short. Completing restore_systems first force-repairs battery_cells and removes that training opportunity. Cook/field_medic remain repair0/96 after both objective events, cannot start any of the18 repairs (minimum1), and have no identified normal repair0 XP producer; this is a new-profile progression trap candidate, not a completed natural-run reproduction. Communication/signal can start repair1 after objectives but remain below repair2 with these finite opportunities. Hazard-induced future damage, probabilistic additional loot and owned hub bonuses are separate conditional sources, not granted here.','', 'Title unlocks: salvage_captain requires scavenge_container log at EndRun; field_medic requires perform_surgery (currently source-less gauze dependency); signal_specialist requires decode_signal voice log. All11 catalog objects can be configured directly; that does not make the3 unlockable classes fresh-title choices.','', 'All62 recipes use AND ingredients; none use alternative OR inputs. Fresh exact-input checks succeeded at required tier; removing1 unit of any listed ingredient rejected every recipe. Effective installed tier2 is derived correctly, but spatial TryCraftRecipe still returnsfalse while direct CanCraft(actualTier2) returns true. Explicit unknown knowledge rejects; null knowledge accepts.','', '## Exact deconstruction','', '| Selection | Required input | Single chosen output | Paired craft/deconstruct net |','|---|---|---|---|']
for x in pairs:lines.append('| '+x['deconstruct']+' | '+str(x['inputs'])+' | '+str(x['chosen_output'])+' | '+str([p['net_items'] for p in x['craft_roundtrips']])+' |')
lines+=['','All7 execute immediately through salvage station with no player skill or power/time gate; authored batch_size is not an additional multiplier. They are single-output recipes. The4 junk definitions are the separate multi-yield path. Every paired roundtrip spends at least one input; no self-sustaining duplication was demonstrated. Plating gains1 scrap at cost1 adhesive; power-cell roundtrip returns its2 wiring but spends1 scrap+1 gel. Other roundtrips also spend reagents; sensor/nozzle/cutter crafting is already unavailable through missing inputs and/or tier gate. Coolant output2 from input1 is seeded reagent conversion, requiring2 water+1 gel each time; current seed coolant source is absent. Simple graph cycles cannot prove bootstrap or duplication.','', 'Cancellation consumes inputs without refund, and the cancel API has no live UI/session caller. Truthful partial craft+inventory JSON restore yielded exactly1 cooked_meal and a second finish returned empty. Queue auto-start free consumption remains a disconnected API path.','', '## Published baseline distinction','', 'Progression models, crafting models, deconstruction code and class definitions are identical Git blobs to8dcc. The recipe catalog was60 on baseline; the only2 local additions are lockpick_set and hack_chip recipes. The fixed20-unit home starter supply is LOCAL: baseline used random repair_parts_starter rolls. Reclaimed-home services/boarding paths and home-work continuations are local-changed files and must not be described as published behavior. Full per-evidence-file Git blob comparison is in followup-class-deconstruction-baseline.json.','', 'Fresh-model-experiment-manifest.json records source hashes, current compiled DLL hash, harness/output hashes, SDK/command, seed/classes/settings, expected/actual and proof boundary. No Unity or user saves were touched.']
(O/'class-deconstruction-baseline-followup.md').write_text('\n'.join(lines)+'\n')
print('Followup evidence exported; model/current baseline hashes recorded.')
