import json, pathlib, hashlib, subprocess, datetime
root=pathlib.Path(r'F:\tmp\synaptic-sea-playable'); out=root/'docs/audit-deep/content'; rev='840f14fb4450dcfba2a0bbce7cb8527e7dfa8e48'; baseline='8dcc95c10ab5e08658546319f51f49b4abd256fc'
r=json.loads((out/'predeparture-supplement-model.json').read_text()); prefix='SynapticSea/Assets/_Project/Core/'
refs=[('seal',prefix+'Session/Interactables/BreachSealPoint.cs',76,'TryStart'),('seal_xp',prefix+'Session/Interactables/BreachSealPoint.cs',180,'Complete'),('seal_instantiation',prefix+'Session/RunSession.Crafting.cs',69,'BuildBreachSealPoints'),('authored_cargo','SynapticSea/Assets/StreamingAssets/data/ship_systems/hull_compartments.json',6,'cargo'),('fire_xp',prefix+'Session/Interactables/FireSuppressionPoint.cs',186,'Complete'),('fire_instantiation',prefix+'Session/RunSession.Fire.cs',636,'BuildFireSuppressionPoints'),('fire_seed_skip',prefix+'Session/RunSession.Fire.cs',378,'SeedFiresFromDamage'),('fire_reignite_skip',prefix+'Session/RunSession.Fire.cs',358,'BuildFireContext'),('safety_predicate',prefix+'Session/RunSession.Hazards.cs',198,'HomeSpawnSafetyActive'),('safety_default',prefix+'Session/RunSessionDeps.cs',153,'HomeSpawnSafety'),('repair_direct',prefix+'Session/Interactables/RepairPoint.cs',224,'Complete'),('repair_event',prefix+'Session/RunSession.Crafting.cs',146,'OnRepairCompleted'),('objective_xp',prefix+'Session/RunSession.Objectives.cs',57,'OnObjectiveCompleted'),('dynamic_mount',prefix+'Session/RunSession.WorkAction.cs',809,'TickWorkAction'),('dynamic_dispatch',prefix+'Session/RunSession.WorkAction.cs',850,'TickWorkAction'),('wrench_gate',prefix+'Session/RunSession.WorkAction.cs',217,'TryWorkActionInteract'),('home_actual_event',prefix+'Session/RunSession.HomeExtension.cs',198,'CompleteHomeWork'),('hub_start',prefix+'Session/RunSession.Build.cs',210,'ConfigurePlayerProgression'),('hub_xp',prefix+'Session/RunSession.Build.cs',223,'ConfigurePlayerProgression'),('hub_purchase','SynapticSea/Assets/_Project/UI/Menus/MenuCoordinator.cs',902,'hub_upgrade_confirm'),('decode',prefix+'Session/RunSession.Crafting.cs',162,'OnVoiceLogPlayed'),('xp_calc',prefix+'Systems/Progression/PlayerProgressionState.cs',165,'GrantXp'),('leadership_unused',prefix+'Systems/Progression/SkillEffectsResolver.cs',271,'XpMultiplier'),('helper_unused',prefix+'Systems/WorkActions/WorkActionDriver.cs',285,'ApplyXp')]
evidence=[]
for key,file,line,symbol in refs:
 b=(root/file).read_bytes(); same=subprocess.run(['git','-c','safe.directory=F:/tmp/synaptic-sea-playable','diff','--quiet',baseline,rev,'--',file],cwd=root).returncode==0
 evidence.append(dict(key=key,file=file,line=line,symbol=symbol,revision=rev,sha256=hashlib.sha256(b).hexdigest(),same_file_blob_as_published_baseline=same))
for x in r['rows']:
 v=x['after_available_repairs']; x['additional_effective_xp_for_repair2']=max(0,200-v['xp']-v['fractional']) if v['level']==1 else 0
 x['normal_traversal_witness']=False; x['classification']='source-connected finite-cache MODEL feasible' if x['repair2'] else 'finite-cache MODEL insufficient; broader normal predeparture exhaustion NOT established'
r['source_refs']=evidence;r['default_home_fires_available']=False;r['home_safety_expiry']='No timer: permanent predicate while home and knob>0';r['live_repair_producers']=[{'producer':'cargo breach seal','xp':15,'mode':'direct class multiplier, no cross penalty','normal_source':'initial authored cargo breach, one cache sealant; strict radius,4s channel; no level gate'},{'producer':'fire suppression','xp':10,'mode':'direct class multiplier, no cross penalty','normal_source':'requires actual burning compartment+cache extinguisher+charge; default home safety prevents seed/reignite; vent grants no repairXP'},{'producer':'repair completion','xp':'25 direct +50 training bus','normal_source':'broken subcomponent, declared minimum repairlevel, actual parts/tools; current cache source finite'},{'producer':'restore_systems/stabilize_reactor objective','xp':'120 each training bus','normal_source':'actual objective completion; repair gate absent on objective; scripted mapped system repairs remove future training opportunities'},{'producer':'mount_component dynamic event','xp':'45 training bus','normal_source':'session wired, wrench/tool_wrench unavailable in current enumerated normal sources; mounted itemform dependency'},{'producer':'owned hub_drydock','xp':None,'effective_starting_level_bonus':1,'normal_source':'owned persistent upgrade applied only Configure; prerequisite closure costs1200 meta currency'},{'producer':'owned hub_reactor_booster','xp':None,'technical_multiplier_bonus':1.1,'normal_source':'owned persistent upgrade applied only Configure; workshop75+reactor150=225 meta currency'}]
r['excluded_false_producers']=['decode_signal trains signal_analysis100, not repair; no XP spillover','repair skill has no tree prerequisite/book requirement; fabrication prerequisite is repair2, not reverse','BreachSealPoint WorkActionChannel patch_breach does not emit authored repair45; actual direct15 only','FireSuppressionPoint WorkActionChannel suppress_fire does not emit authored repair45; actual direct10 only','commission_home_propulsion authored repair event overridden by actual CompleteHomeWork weld_panel; trains welding, not repair','secure_connection emits weld_panel; cut_web_attachment emits decontaminate_zone; neither trains repair','splice_conduit absent normal interaction selection; RunWorkAction immediate API has no production caller','WorkActionDriver.ApplyXp fallback15 has no caller; SkillEffectsResolver.XpMultiplier leadership formula has no caller; neither counted','GrantXpFromBook no live caller; book definitions unregistered and without normal acquisition; not counted','dismount/cut/pry emit salvage->scavenging; weld_patch emits weld_panel->welding; plant/harvest target cooking']
(out/'predeparture-repair-producers.json').write_text(json.dumps(r,indent=2)+'\n')
lines=['# Predeparture repair source correction', '',f'Revision `{rev}`. This supersedes the earlier no-repair0-producer/trap candidate wording. Freshly compiled current Core, actual catalogs and finite authored cache; no Unity, natural input walk, user profile or grant of fire/hub perk. Cargo seal uses actual BreachSealPoint and repairs actual RepairPoint completion handlers. All11 class objects configured; three locked titles remain locked on fresh meta.', '', 'Normal source traced: initial cargo hull health0.3/breach_open=true -> BuildBreachSealPoints -> normal interaction registry -> strict-range4s seal consuming1 of cache6 hull_sealant -> repairXP15 directly, without cross penalty. Cargo source is finite. Fire suppression gives direct repairXP10 but default HomeSpawnSafety=1 permanently skips home fire seeds/reignition; there is no safety expiry clock. Authored channel xp_event repair45 is not additionally emitted by either wrapper.', '', '| Class | After cargo seal level/XP/fraction | Final finite-cache model level/XP/fraction | Repair2 | Remaining effective XP | Natural walk witnessed |', '|---|---|---|---|---:|---|']
for x in r['rows']:
 f=lambda d:f"{d['level']}/{d['xp']}/{d['fractional']:.3f}"
 lines.append(f"| {x['class']} {'(title locked)' if x['title_locked'] else ''} | {f(x['after_cargo_seal'])} | {f(x['after_available_repairs'])} | {'model feasible' if x['repair2'] else 'model insufficient'} | {x['additional_effective_xp_for_repair2']:.3f} | no |")
lines += ['', 'Sequence: greedily source-feasible repairs from the authored cache before objective XP; emit exact two120XP objective events and mirror their mapped force-repairs; perform cargo seal; finish newly source-feasible repairs. No random cache roll, repeated hazard damage, remount, skill books, hub perks or fire granted. Engineer/mechanic/scientist begin above gate; pilot/salvage captain require preserving low-level repair opportunities before scripted objective repairs; security reaches2 through cargo seal. Cook/field_medic bootstrap from0/96 to1/8 through cargo seal, then star_charts to1/48. Medic/communications/signal specialist remain below2 in this finite-cache model. These unsatisfied edges are NOT proof of global normal-run deadlock: runtime/system damage, other finite random rolls and existing meta need separate source-and-input experiments.', '', 'Owned hub reactor booster multiplies technical XP1.1; owned drydock adds1 repair at new-run configuration. Booster requires225 meta currency total; drydock prerequisite closure totals1200 (workshop75+medical75+scanner100+armory100+reactor150+command300+drydock400). Live menu purchase is connected but these are existing persistent meta, never assumed on a new profile. Leadership XP formula is unused; class technical multiplier and bus cross-training are live. Decode grants signal_analysis, without repair spillover. Repair has no skill-tree/book prerequisite.', '', 'All live producers and excluded misleading definition/helper paths are enumerated in predeparture-repair-producers.json. In particular mount_component repair45 is dynamically emitted by session completion but lacks a normal wrench source; commission_home_propulsion actually emits weld_panel (welding), despite authored repair xp_event.', '', 'Highest-value discriminator: security natural predeparture cache acquisition -> battery_cells and star_charts repair BEFORE restore_systems objective -> two onboarding completions -> cargo seal -> nav_linkage repair2. Compare cook cargo seal bootstrap and default zero burning home compartments. No report may convert this model witness into a natural walk witness.', '', 'Exact evidence (file:line:symbol):']
lines += [f"- `{e['file']}:{e['line']}:{e['symbol']}` (same published file: {e['same_file_blob_as_published_baseline']})." for e in evidence]
(out/'predeparture-repair-producers.md').write_text('\n'.join(lines)+'\n')
files=sorted((root/'SynapticSea/Assets/_Project/Core').rglob('*.cs'))+sorted((root/'SynapticSea/Assets/StreamingAssets/data').rglob('*.json')); hashes={str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
manifest=dict(revision=rev,git_dirty_tracked=subprocess.check_output(['git','-c','safe.directory=F:/tmp/synaptic-sea-playable','diff','--name-only'],cwd=root,text=True).splitlines(),source_data_hash=hashlib.sha256(json.dumps(hashes,sort_keys=True).encode()).hexdigest(),source_data_hashes=hashes,compiled_artifact=str(out/'supplement-bin/net8.0/Supplement.dll'),artifact_sha256=hashlib.sha256((out/'supplement-bin/net8.0/Supplement.dll').read_bytes()).hexdigest(),harness_sha256=hashlib.sha256((out/'Supplement.cs').read_bytes()).hexdigest(),result_sha256=hashlib.sha256((out/'predeparture-supplement-model.json').read_bytes()).hexdigest(),profile=None,seed=17,classes='all11 configured directly; title locks not bypassed in claimed normal play',settings='condition1, opening propulsion override; no hub perks/fire',sequence=r['scope'],expected='authored cargo seal completes, consumes1 sealant, gives direct15 class-multiplied repairXP; security crosses repair2; zero classes bootstrap repair1',actual='all11 seal complete; security repair2; cook/field_medic repair1; exact results attached',unity_executed=False,user_save_writes=False,command='F:\\Tools\\dotnet\\dotnet.exe build docs/audit-deep/content/Supplement.csproj --verbosity quiet; dotnet docs/audit-deep/content/supplement-bin/net8.0/Supplement.dll <repo> <contentdir>',compiled_build_result='success, warning MSB3539 paths all inside audit dir')
(out/'predeparture-supplement-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
old=out/'class-deconstruction-baseline-followup.md'; txt=old.read_text(); txt=txt.replace('have no identified normal repair0 XP producer; this is a new-profile progression trap candidate, not a completed natural-run reproduction.', 'DO have the live cargo breach seal repair0 XP producer, discovered in the supplemental followup. The earlier progression trap candidate is superseded by predeparture-repair-producers.md; no deadlock is established.')
old.write_text(txt)
print('Supplement exported; classes',len(r['rows']),'sources',len(evidence),'DLL',manifest['artifact_sha256'])

