using System;using System.IO;using System.Collections.Generic;using SynapticSea.Core.Services;using SynapticSea.Core.Systems;using SynapticSea.Core.Variant;using SynapticSea.Core.Session;
class Program{
static GdDict Copy(GdDict d)=>(GdDict)GdJson.Parse(GdJson.Stringify(d));
static InventoryState Starter(){var inv=new InventoryState();var home=CatalogRegistry.LoadDict("res://data/procgen/golden/coherent_ship_001/gameplay_slice.json");foreach(GdDict box in home.GetArrayOrEmpty("loot_containers"))foreach(GdDict item in box.GetArrayOrEmpty("contents"))inv.AddItem(item.GetString("item_id"),item.GetInt("qty"));return inv;}
static PlayerProgressionState Prog(ClassDefinition c){var p=new PlayerProgressionState();p.Configure(c,PlayerProgressionState.LoadSkillsCatalog(),PlayerProgressionState.LoadBooksCatalog());return p;}
static TrainingEventBus Bus(){var b=new TrainingEventBus();b.Configure();return b;}
static ShipSystemsManager Opening(){var m=new ShipSystemsManager();m.Configure(m.LoadDefinitions(),1,17);foreach(var sub in m.GetSystem("propulsion").Subcomponents)sub.Health=1; m.GetSystem("propulsion").GetSubcomponent("nav_linkage").Health=.2;return m;}
static GdDict Skill(PlayerProgressionState p)=>new GdDict{{"repair_level",p.GetSkillLevel("repair")},{"repair_xp",p.GetSkillXp("repair")},{"fractional",p.SkillXpFractional.Get("repair",0.0)},{"fabrication_level",p.GetSkillLevel("fabrication")},{"cross_training_repair",p.GetCrossTraining("repair")}};
static void Main(string[] a){CoreServices.Resources=new FileSystemResourceReader(Path.Combine(a[0],"SynapticSea","Assets","StreamingAssets"));var rows=new GdArray();var classes=ClassDefinition.LoadAll();foreach(var c in classes.Values){var p=Prog(c);var b=Bus();var initial=Skill(p);b.Emit("repair_full_system","2",p);b.Emit("repair_full_system","4",p);var objectives=Skill(p);var start=Starter();var manager=Opening();manager.ForceRepair("power","power_distribution");manager.ForceRepair("power","battery_cells");manager.ForceRepair("power","reactor_core");manager.ForceRepair("navigation","nav_computer");var eligible=new GdArray();foreach(var sid in manager.SystemOrder)foreach(var sub in manager.GetSystem(sid).Subcomponents)if(!sub.IsFunctional()){var rp=new RepairPoint();rp.Configure(sid,sub.SubcomponentId,manager,start,p,Vec3.Zero,sub.RepairSeconds,sub.MinSkill);if(rp.CanBeginRepair())eligible.Add(sid+"/"+sub.SubcomponentId);}
// Alternate order diagnostic: spend finite authored cache to repair source-feasible broken subs before the two objective XP grants. This is NOT a walk or UI experiment.
var alt=Prog(c);var ab=Bus();var am=Opening();var bag=Starter();var done=new GdArray();for(int pass=0;pass<18;pass++){bool changed=false;foreach(var sid in am.SystemOrder)foreach(var sub in am.GetSystem(sid).Subcomponents){if(sub.IsFunctional())continue;var rp=new RepairPoint();rp.Configure(sid,sub.SubcomponentId,am,bag,alt,Vec3.Zero,sub.RepairSeconds,sub.MinSkill);if(!rp.CanBeginRepair())continue;var result=am.RepairWithInventory(sid,sub.SubcomponentId,bag,alt.GetSkillLevel("repair"));if(!result.GetBool("success"))continue;alt.GrantXp("repair",25);ab.Emit("repair_subcomponent",sid+"."+sub.SubcomponentId,alt);done.Add(sid+"/"+sub.SubcomponentId);changed=true;}if(!changed)break;}ab.Emit("repair_full_system","2",alt);ab.Emit("repair_full_system","4",alt);
rows.Add(new GdDict{{"class_id",c.ClassId},{"unlockable",c.Unlockable},{"initial",initial},{"after_exact_two_onboarding_xp_events",objectives},{"repair2_skill_after_objectives",p.GetSkillLevel("repair")>=2},{"broken_subs_eligible_using_authored_cache_after_objective_xp_only",eligible},{"alternative_cache_repair_before_objective_sequence",done},{"alternative_progression",Skill(alt)},{"alternative_bag_remaining",bag.GetSummary()},{"onboarding_log",b.GetLog()}});}
var craft=new CraftingState();var decon=new DeconstructionResolver();var andRows=new GdArray();var dr=new GdArray();foreach(object raw in craft.GetAllRecipeIds()){string id=V.Str(raw);var r=craft.GetRecipe(id);var ingredients=r.GetDictOrEmpty("ingredients");var full=new InventoryState();foreach(var kv in ingredients)full.AddItem(V.Str(kv.Key),V.I64(kv.Value));bool exact=craft.CanCraft(id,full,null,craft.GetStationTierMin(id));var missing=new GdArray();foreach(var kv in ingredients){var one=new InventoryState();one.ApplySummary(Copy(full.GetSummary()));one.RemoveItem(V.Str(kv.Key),1);missing.Add(new GdDict{{"removed",V.Str(kv.Key)},{"can_craft",craft.CanCraft(id,one,null,craft.GetStationTierMin(id))}});}andRows.Add(new GdDict{{"recipe_id",id},{"exact_all_inputs_can_craft",exact},{"missing_one_each",missing},{"default_tier_can_craft",craft.CanCraft(id,full)},{"required_tier",craft.GetStationTierMin(id)}});
if(r.GetString("category")=="deconstruction"){var before=Copy(full.GetSummary());var st=new CraftingStation();st.Configure("salvage",craft,new MaterialState(),full,decon,null,Vec3.Zero,1.8);bool ok=st.TrySalvageTarget(id);dr.Add(new GdDict{{"recipe_id",id},{"before",before},{"after",full.GetSummary()},{"ok",ok},{"authored_ingredients",ingredients},{"authored_produces",r.GetDictOrEmpty("produces")},{"authored_batch_size",r.GetInt("batch_size",1)},{"authored_duration",r.Get("craft_time_seconds",0.0)},{"actual_duration_ticks",0L},{"class_skill_supplied",0L}});}}
var knowledge=new RecipeKnowledgeState();var all=new GdDict();foreach(object raw in craft.GetAllRecipeIds())all[V.Str(raw)]=craft.GetRecipe(V.Str(raw));knowledge.SeedFromRecipes(all);var ki=new InventoryState();var kr=craft.GetRecipe("craft_thruster_nozzle");foreach(var kv in kr.GetDictOrEmpty("ingredients"))ki.AddItem(V.Str(kv.Key),V.I64(kv.Value));var kg=new GdDict{{"book_recipe_known",knowledge.IsKnown("craft_thruster_nozzle")},{"with_knowledge_can_craft",craft.CanCraft("craft_thruster_nozzle",ki,knowledge,2)},{"without_knowledge_can_craft",craft.CanCraft("craft_thruster_nozzle",ki,null,2)}};
var ci=new InventoryState();ci.AddItem("ration_pack",1);ci.AddItem("purified_water",1);var cbefore=Copy(ci.GetSummary());bool begun=craft.BeginCraft("cook_basic_meal",ci,new MaterialState(),0);var half=Copy(craft.GetSummary());craft.CancelCraft();var cancel=new GdDict{{"recipe_id","cook_basic_meal"},{"begun",begun},{"before",cbefore},{"after_cancel",ci.GetSummary()},{"summary_before_cancel",half},{"summary_after_cancel",craft.GetSummary()}};
var replayCraft=new CraftingState();var replayInv=new InventoryState();replayInv.AddItem("ration_pack",1);replayInv.AddItem("purified_water",1);replayCraft.BeginCraft("cook_basic_meal",replayInv,new MaterialState(),0);replayCraft.Tick(5);var savedCraft=Copy(replayCraft.GetSummary());var savedBag=Copy(replayInv.GetSummary());var restoredCraft=new CraftingState();restoredCraft.ApplySummary(savedCraft);var restoredBag=new InventoryState();restoredBag.ApplySummary(savedBag);restoredCraft.Tick(5);var first=restoredCraft.FinishCraft();restoredBag.AddItem(first.GetString("item_id"),first.GetInt("quantity"));var second=restoredCraft.FinishCraft();var repeat=new GdDict{{"saved_craft",savedCraft},{"saved_inventory",savedBag},{"first_finish",first},{"second_finish",second},{"final_inventory",restoredBag.GetSummary()}};var tierCatalog=new ComponentCatalog();tierCatalog.LoadDefault();var placed=GdArray.Of(new GdDict{{"component_id","reactor_console"},{"mounted",true}});long actualTier=craft.RefreshStationTier("fabricator",placed,tierCatalog);var tierStation=new CraftingStation();tierStation.Configure("fabricator",craft,new MaterialState(),ki,decon,null,Vec3.Zero,1.8);var tierP=new PlayerProgressionState();tierP.Configure(classes["mechanic"],PlayerProgressionState.LoadSkillsCatalog());tierP.Skills["fabrication"]=10L;tierStation.PlayerProgression=tierP;bool viaStation=tierStation.TryCraftRecipe("craft_thruster_nozzle");var tierCheck=new GdDict{{"effective_tier",actualTier},{"direct_can_craft_at_actual_tier",craft.CanCraft("craft_thruster_nozzle",ki,null,actualTier)},{"spatial_station_try_craft",viaStation}};var modelOutput=new GdDict{{"revision","840f14fb4450dcfba2a0bbce7cb8527e7dfa8e48"},{"scope","freshly compiled engine-free current Core; model diagnostic; NO natural traversal/input/access assertions"},{"seed",17L},{"class_rows",rows},{"recipe_AND_checks",andRows},{"all7_deconstruction_station_transactions",dr},{"knowledge_gate_diagnostic",kg},{"cancel_transaction",cancel},{"craft_save_once_guard",repeat},{"station_tier_gate",tierCheck}};File.WriteAllText(Path.Combine(a[1],"fresh-model-results.json"),GdJson.Stringify(modelOutput));Console.WriteLine("Class rows="+rows.Count+" recipes="+andRows.Count+" decon="+dr.Count);}}


