using System;
using System.Collections.Generic;
using UnityEngine;

namespace SynapticSea.Runtime
{
    /// <summary>
    /// Maps the Godot audio resource paths (<c>res://data/audio/...</c>) that data and code reference onto imported
    /// Unity clips, so clips ship in builds and nothing loads WAVs from disk at runtime. Regenerated by the Editor
    /// AudioCatalogBuilder from <c>Assets/Content/Audio</c>.
    /// </summary>
    [CreateAssetMenu(menuName = "Synaptic Sea/Audio Catalog", fileName = "AudioCatalog")]
    public sealed class AudioCatalog : ScriptableObject
    {
        [Serializable]
        public sealed class Entry
        {
            public string resPath;
            public AudioClip clip;
        }

        public List<Entry> entries = new List<Entry>();

        Dictionary<string, AudioClip> _byPath;

        public bool TryGetClip(string resPath, out AudioClip clip)
        {
            if (_byPath == null)
            {
                _byPath = new Dictionary<string, AudioClip>(StringComparer.Ordinal);
                foreach (var e in entries)
                    if (e != null && !string.IsNullOrEmpty(e.resPath) && e.clip != null) _byPath[e.resPath] = e.clip;
            }
            return _byPath.TryGetValue(resPath ?? string.Empty, out clip);
        }

        void OnValidate() => _byPath = null;
    }
}
