using System.IO;
using UnityEditor;
using UnityEngine;

namespace SynapticSea.EditorTools.Bootstrap
{
    /// <summary>
    /// Enables C# wrapper generation for Assets/Content/Input/SynapticSea.inputactions (generated by
    /// tools/python/gen_input_actions.py) so runtime code uses a typed <c>SynapticSeaInput</c> class.
    ///   Unity.exe -batchmode -projectPath SynapticSea -executeMethod SynapticSea.EditorTools.Bootstrap.InputSetup.Apply -quit
    /// </summary>
    public static class InputSetup
    {
        const string AssetPath = "Assets/Content/Input/SynapticSea.inputactions";
        const string WrapperPath = "Assets/_Project/Runtime/Input/SynapticSeaInput.cs";

        [MenuItem("Synaptic Sea/Bootstrap/Configure Input Actions")]
        public static void Apply()
        {
            AssetDatabase.ImportAsset(AssetPath, ImportAssetOptions.ForceUpdate);
            var importer = AssetImporter.GetAtPath(AssetPath);
            if (importer == null)
            {
                Debug.LogError($"[InputSetup] no importer for {AssetPath}");
                if (Application.isBatchMode) EditorApplication.Exit(1);
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(WrapperPath));
            var so = new SerializedObject(importer);
            bool ok = Set(so, "m_GenerateWrapperCode", true)
                      & Set(so, "m_WrapperCodePath", WrapperPath)
                      & Set(so, "m_WrapperClassName", "SynapticSeaInput")
                      & Set(so, "m_WrapperCodeNamespace", "SynapticSea.Runtime.Input");
            so.ApplyModifiedPropertiesWithoutUndo();
            importer.SaveAndReimport();

            Debug.Log($"[InputSetup] INPUT SETUP {(ok && File.Exists(WrapperPath) ? "PASS" : "FAIL")} wrapper={WrapperPath}");
            if (Application.isBatchMode) EditorApplication.Exit(ok && File.Exists(WrapperPath) ? 0 : 1);
        }

        static bool Set(SerializedObject so, string name, object value)
        {
            var p = so.FindProperty(name);
            if (p == null)
            {
                Debug.LogError($"[InputSetup] importer property {name} not found");
                return false;
            }
            if (value is bool b) p.boolValue = b;
            else p.stringValue = (string)value;
            return true;
        }
    }
}
